services:
  nginx-api-gw-debug:
    container_name: nginx-api-gw-debug
    image: nginx-api-gw-debug:v1.0
    ports:
      - "8443:8443"
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /home/apps/docker/nginx/webplatform/etc/conf/code-server:/home/coder/.config/code-server
    command: ["bash", "/usr/local/bin/init.sh"]
    restart: always
    privileged: true
    networks:
      - 1panel-network

networks:
    1panel-network:
        external: true