version: '3.8'

services:
  web:
    image: webplatform-gw-debug:1.0.0
    container_name: nginx-api-gw
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/gw/nginx/conf.d:/etc/nginx/conf.d
      - ./:/home/gvsun/webplatform
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    networks:
      - my-bridge-network
    restart: always
    
networks:
  my-bridge-network:
    driver: bridge
