version: '3.8'

services:
  web:
    image: nginx-api-gw:v1.0
    container_name: nginx-api-gw
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - ./cache:/var/nginx/cache
      - ../../:/home/gvsun/webplatform
    networks:
      - 1panel-network
    restart: always

networks:
    1panel-network:
        external: true