version: '3.8'

services:
  web:
    image: srshookweb:v1.0
    container_name: srshookweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10080:10080/udp" 
      - "1935:1935"       
      - "1985:1985"
      - "5060:5060"
      - "8000:8000/udp"   
      - "8088:8080"
      - "9000:9000"
    volumes:
      - ./srs.conf:/usr/local/srs/conf/srs.conf
      - ./init.sh:/home/gvsun/webplatform/docker/srshookweb/init.sh
    networks:
      - my-bridge-network
    restart: unless-stopped

networks:
  my-bridge-network:
    driver: bridge