version: '3.8'

services:
  web:
    image: ubuntu-iot:v1.0
    container_name: ubuntu-iot-debug
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
      - "8022:8888"
    volumes:
      - ../../:/home/gvsun/webplatform
    networks:
      - 1panel-network
    restart: always

networks:
    1panel-network:
        external: true
